name: Publish to npm

on:
  push:
    tags:
      - "@didhq/did-render-sdk*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm i -r

      - name: Cd to packages/sdk
        run: cd packages/sdk

      - name: Build your package
        run: pnpm run build

      - name: git status
        run: git status

      - name: Publish to npm
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
